// Navigation configuration: maps nav item names to routes
export interface NavItem {
  name: string;
  path: string;
}

export const navItems: NavItem[] = [
  { name: "Home", path: "/" },
  { name: "Amplifiers", path: "/amplifiers/" },
  { name: "Speakers", path: "/speakers/" },
  { name: "Subwoofers", path: "/subwoofers/" },
  { name: "Sleds", path: "/sleds/" },
  { name: "Support", path: "/support/" },
];

// Helper: convert a nav name to a route path
export function getRouteByName(name: string): string {
  const item = navItems.find(
    (n) => n.name.toLowerCase() === name.toLowerCase()
  );
  return item ? item.path : "/";
}

// Map category card names (which may differ from nav names) to routes
export function getCategoryRoute(name: string): string {
  const lower = name.toLowerCase();
  if (lower.includes("amplifier")) return "/amplifiers/";
  if (lower.includes("speaker")) return "/speakers/";
  if (lower.includes("subwoofer") || lower.includes("sub")) return "/subwoofers/";
  if (lower.includes("sled") || lower.includes("enclosure")) return "/sleds/";
  if (lower.includes("wiring") || lower.includes("accessor") || lower.includes("kit")) return "/sleds/";
  if (lower.includes("support") || lower.includes("faq") || lower.includes("contact")) return "/support/";
  return "/";
}

// Map a product's series/name to the most relevant category page
export function getProductRoute(productName: string, series: string): string {
  const combined = (productName + " " + series).toLowerCase();
  // Check wiring/kit/gauge first (before "amp" which appears in "Amp Kit")
  if (combined.includes("wiring") || combined.includes("gauge") || (combined.includes("kit") && !combined.includes("amplifier"))) return "/sleds/";
  if (combined.includes("sled") || combined.includes("enclosure") || combined.includes("package")) return "/sleds/";
  if (combined.includes("meso-12") || combined.includes("meso-10") || combined.includes("meso-15") || combined.includes("subwoofer") || combined.includes("sub")) return "/subwoofers/";
  if (combined.includes("speaker") || combined.includes("tweeter") || combined.includes("6x9") || combined.includes("meso-6")) return "/speakers/";
  if (combined.includes("amplifier") || combined.includes("2000.1d") || combined.includes("200.4d") || combined.includes("1000.4d") || combined.includes("1200.1d")) return "/amplifiers/";
  return "/amplifiers/";
}

// Category data for product category pages
export interface CategoryPageData {
  title: string;
  accent: string;
  subtitle: string;
  heroImage: string;
  description: string;
  products: ProductCardData[];
}

export interface ProductCardData {
  badge: string;
  series: string;
  name: string;
  slug: string;
  description: string;
  rating: number;
  reviews: number;
  currentPrice: string;
  originalPrice: string;
  image: string;
}

// Product detail data for individual product pages
export interface ProductDetailData {
  name: string;
  slug: string;
  series: string;
  category: string;
  categorySlug: string;
  badge: string;
  shortDesc: string;
  longDesc: string;
  rating: number;
  reviews: number;
  currentPrice: string;
  originalPrice: string;
  image: string;
  specs: { label: string; value: string }[];
  features: string[];
  whatsIncluded: string[];
  inStock: boolean;
}

// All product detail data keyed by slug
export const productDetails: Record<string, ProductDetailData> = {
  "abcde-2000-1d": {
    name: "ABCDE-2000.1D",
    slug: "abcde-2000-1d",
    series: "ABCDE Series",
    category: "Amplifiers",
    categorySlug: "amplifiers",
    badge: "Best Seller",
    shortDesc: "2000W RMS Monoblock Class D Amplifier",
    longDesc: "The ABCDE-2000.1D is a powerhouse monoblock Class D amplifier designed for serious bass enthusiasts. With 2000W RMS of clean power, this amplifier features advanced thermal protection, precision crossover controls, and a compact chassis that fits easily under most seats. The built-in bass boost and subsonic filter give you complete control over your low-end response.",
    rating: 5,
    reviews: 127,
    currentPrice: "$299.99",
    originalPrice: "$449.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
    specs: [
      { label: "RMS Power @ 1 Ohm", value: "2000W" },
      { label: "RMS Power @ 2 Ohm", value: "1000W" },
      { label: "Topology", value: "Class D" },
      { label: "Channels", value: "1 (Monoblock)" },
      { label: "Signal-to-Noise Ratio", value: "> 90 dB" },
      { label: "Frequency Response", value: "10Hz - 250Hz" },
      { label: "THD", value: "< 0.1%" },
      { label: "Damping Factor", value: "> 200" },
      { label: "Crossover Type", value: "Low-Pass (50Hz - 250Hz)" },
      { label: "Subsonic Filter", value: "15Hz - 50Hz" },
      { label: "Bass Boost", value: "0 - 12 dB @ 45Hz" },
      { label: "Input Sensitivity", value: "0.2V - 6V" },
      { label: "Dimensions", value: '10.5" x 6.5" x 2.2"' },
      { label: "Weight", value: "6.8 lbs" },
    ],
    features: [
      "2000W RMS at 1 Ohm stable",
      "Advanced Class D topology for maximum efficiency",
      "Precision low-pass crossover with subsonic filter",
      "Variable bass boost (0-12 dB) at 45Hz",
      "Thermal and short-circuit protection circuitry",
      "Compact chassis design for flexible installation",
      "High-level inputs with auto turn-on",
      "Nickel-plated terminal blocks for maximum conductivity",
    ],
    whatsIncluded: ["ABCDE-2000.1D Amplifier", "Remote Bass Knob with Cable", "Mounting Hardware Kit", "User Manual"],
    inStock: true,
  },
  "atv2-200-4d": {
    name: "ATv2-200.4D",
    slug: "atv2-200-4d",
    series: "AT Series v2",
    category: "Amplifiers",
    categorySlug: "amplifiers",
    badge: "New",
    shortDesc: "4-Channel Class D Amplifier",
    longDesc: "The ATv2-200.4D delivers 200W RMS per channel across four channels, making it perfect for powering a full speaker system. The second generation AT Series features improved sound quality, enhanced crossover flexibility, and a sleek new chassis design. Bridge channels for more power or run all four independently for complete system control.",
    rating: 4,
    reviews: 54,
    currentPrice: "$229.99",
    originalPrice: "$329.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
    specs: [
      { label: "RMS Power @ 4 Ohm", value: "100W x 4" },
      { label: "RMS Power @ 2 Ohm", value: "200W x 4" },
      { label: "RMS Bridged @ 4 Ohm", value: "400W x 2" },
      { label: "Topology", value: "Class D" },
      { label: "Channels", value: "4" },
      { label: "Signal-to-Noise Ratio", value: "> 95 dB" },
      { label: "Frequency Response", value: "10Hz - 40kHz" },
      { label: "THD", value: "< 0.05%" },
      { label: "Crossover Type", value: "High-Pass / Low-Pass / Full" },
      { label: "Input Sensitivity", value: "0.2V - 6V" },
      { label: "Dimensions", value: '9.8" x 6.2" x 2.0"' },
      { label: "Weight", value: "5.5 lbs" },
    ],
    features: [
      "200W RMS x 4 channels at 2 Ohm",
      "Bridgeable to 400W x 2 at 4 Ohm",
      "Independent crossover controls for front/rear channels",
      "High-pass, low-pass, and full-range selectable",
      "Compact Class D design runs cool and efficient",
      "Auto-sensing turn-on for OEM integration",
      "Gold-plated RCA inputs and speaker terminals",
      "2nd generation improved sound circuitry",
    ],
    whatsIncluded: ["ATv2-200.4D Amplifier", "Mounting Hardware Kit", "Hex Wrench", "User Manual"],
    inStock: true,
  },
  "abcde-1000-4d": {
    name: "ABCDE-1000.4D",
    slug: "abcde-1000-4d",
    series: "ABCDE Series",
    category: "Amplifiers",
    categorySlug: "amplifiers",
    badge: "",
    shortDesc: "1000W 4-Channel Class D Amplifier",
    longDesc: "The ABCDE-1000.4D is a premium 4-channel amplifier delivering 250W RMS per channel at 2 Ohm load. Built with audiophile-grade components and advanced Class D technology, it combines raw power with pristine sound quality. Perfect for high-end component speaker systems or bi-amped front stage setups.",
    rating: 5,
    reviews: 89,
    currentPrice: "$199.99",
    originalPrice: "$279.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
    specs: [
      { label: "RMS Power @ 4 Ohm", value: "125W x 4" },
      { label: "RMS Power @ 2 Ohm", value: "250W x 4" },
      { label: "RMS Bridged @ 4 Ohm", value: "500W x 2" },
      { label: "Topology", value: "Class D" },
      { label: "Channels", value: "4" },
      { label: "Signal-to-Noise Ratio", value: "> 92 dB" },
      { label: "Frequency Response", value: "10Hz - 40kHz" },
      { label: "THD", value: "< 0.08%" },
      { label: "Crossover Type", value: "HPF / LPF / Full Range" },
      { label: "Input Sensitivity", value: "0.2V - 6V" },
      { label: "Dimensions", value: '10.2" x 6.4" x 2.1"' },
      { label: "Weight", value: "5.9 lbs" },
    ],
    features: [
      "1000W total RMS across 4 channels",
      "Premium audiophile-grade components",
      "Independent front/rear crossover controls",
      "Bridgeable output for subwoofer applications",
      "Advanced thermal management system",
      "DC offset and overload protection",
      "OEM integration friendly with high-level inputs",
      "Sleek brushed aluminum finish",
    ],
    whatsIncluded: ["ABCDE-1000.4D Amplifier", "Mounting Hardware Kit", "Hex Wrench Set", "User Manual"],
    inStock: true,
  },
  "at-1200-1d": {
    name: "AT-1200.1D",
    slug: "at-1200-1d",
    series: "AT Series",
    category: "Amplifiers",
    categorySlug: "amplifiers",
    badge: "Sale",
    shortDesc: "1200W RMS Monoblock Amplifier",
    longDesc: "The AT-1200.1D offers an excellent balance of power and value, delivering 1200W RMS at 1 Ohm. This monoblock amplifier is engineered for reliable daily use with robust protection circuits and efficient Class D design. An ideal choice for entry to mid-level subwoofer builds.",
    rating: 4,
    reviews: 67,
    currentPrice: "$159.99",
    originalPrice: "$229.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
    specs: [
      { label: "RMS Power @ 1 Ohm", value: "1200W" },
      { label: "RMS Power @ 2 Ohm", value: "600W" },
      { label: "Topology", value: "Class D" },
      { label: "Channels", value: "1 (Monoblock)" },
      { label: "Signal-to-Noise Ratio", value: "> 85 dB" },
      { label: "Frequency Response", value: "15Hz - 200Hz" },
      { label: "THD", value: "< 0.15%" },
      { label: "Crossover Type", value: "Low-Pass (40Hz - 200Hz)" },
      { label: "Bass Boost", value: "0 - 9 dB @ 45Hz" },
      { label: "Input Sensitivity", value: "0.3V - 6V" },
      { label: "Dimensions", value: '9.5" x 5.8" x 2.0"' },
      { label: "Weight", value: "4.8 lbs" },
    ],
    features: [
      "1200W RMS at 1 Ohm load",
      "Efficient Class D topology",
      "Variable low-pass crossover",
      "Bass boost up to 9 dB",
      "Thermal, short-circuit, and overload protection",
      "Compact footprint fits anywhere",
      "Remote bass knob ready (sold separately)",
      "Great value for daily driver builds",
    ],
    whatsIncluded: ["AT-1200.1D Amplifier", "Mounting Hardware Kit", "User Manual"],
    inStock: true,
  },
  "meso-6-5": {
    name: "MESO-6.5",
    slug: "meso-6-5",
    series: "Meso Series",
    category: "Speakers",
    categorySlug: "speakers",
    badge: "Best Seller",
    shortDesc: "6.5 Inch 2-Way Component Speaker System",
    longDesc: "The MESO-6.5 component speaker system represents the pinnacle of ABCDE speaker engineering. Featuring a woven fiberglass cone, butyl rubber surround, and a precision-tuned crossover network, these speakers deliver studio-quality sound with crystal-clear highs and warm, natural mids. The included 1-inch silk dome tweeters provide smooth, detailed high-frequency reproduction.",
    rating: 5,
    reviews: 94,
    currentPrice: "$149.99",
    originalPrice: "$199.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
    specs: [
      { label: "Size", value: '6.5"' },
      { label: "Type", value: "2-Way Component" },
      { label: "Peak Power", value: "300W" },
      { label: "RMS Power", value: "100W" },
      { label: "Impedance", value: "4 Ohm" },
      { label: "Sensitivity", value: "89 dB" },
      { label: "Frequency Response", value: "45Hz - 22kHz" },
      { label: "Cone Material", value: "Woven Fiberglass" },
      { label: "Surround", value: "Butyl Rubber" },
      { label: "Tweeter", value: '1" Silk Dome' },
      { label: "Crossover", value: "12 dB/octave, 3.5kHz" },
      { label: "Mounting Depth", value: '2.75"' },
    ],
    features: [
      "Woven fiberglass cone for ultimate clarity",
      "1-inch silk dome tweeter with smooth response",
      "Precision 12 dB/octave crossover network",
      "Butyl rubber surround for long life",
      "High-power handling with low distortion",
      "Includes grilles and mounting hardware",
      "Gold-plated speaker terminals",
      "Designed and tuned in the USA",
    ],
    whatsIncluded: ["2 x 6.5\" Woofers", "2 x 1\" Silk Dome Tweeters", "2 x Crossover Networks", "Mounting Hardware", "Grilles", "User Manual"],
    inStock: true,
  },
  "at-6x9": {
    name: "AT-6X9",
    slug: "at-6x9",
    series: "AT Series",
    category: "Speakers",
    categorySlug: "speakers",
    badge: "New",
    shortDesc: "6x9 Inch 3-Way Coaxial Speakers",
    longDesc: "The AT-6X9 3-way coaxial speakers offer exceptional sound quality in an easy-to-install package. With a polypropylene cone woofer, PEI dome midrange, and piezo tweeter, these speakers cover the full frequency range with impressive clarity. Drop-in fit for most factory 6x9 locations makes upgrading your sound system effortless.",
    rating: 4,
    reviews: 41,
    currentPrice: "$89.99",
    originalPrice: "$129.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
    specs: [
      { label: "Size", value: '6"x9"' },
      { label: "Type", value: "3-Way Coaxial" },
      { label: "Peak Power", value: "250W" },
      { label: "RMS Power", value: "80W" },
      { label: "Impedance", value: "4 Ohm" },
      { label: "Sensitivity", value: "92 dB" },
      { label: "Frequency Response", value: "35Hz - 20kHz" },
      { label: "Cone Material", value: "Polypropylene" },
      { label: "Surround", value: "Rubber" },
      { label: "Midrange", value: '1.5" PEI Dome' },
      { label: "Tweeter", value: '0.5" Piezo' },
      { label: "Mounting Depth", value: '3.1"' },
    ],
    features: [
      "3-way design for full-range sound from one speaker",
      "High sensitivity for excellent output on factory power",
      "Drop-in fit for most factory 6x9 locations",
      "Rubber surround for durability",
      "PEI dome midrange for clear vocals",
      "Piezo tweeter extends to 20kHz",
      "Includes grilles and mounting brackets",
      "Great factory speaker upgrade",
    ],
    whatsIncluded: ["2 x 6x9 Speakers", "2 x Grilles", "Mounting Brackets", "Hardware Kit", "User Manual"],
    inStock: true,
  },
  "meso-6": {
    name: "MESO-6",
    slug: "meso-6",
    series: "Meso Series",
    category: "Speakers",
    categorySlug: "speakers",
    badge: "",
    shortDesc: "6.5 Inch Midrange Speaker (Pair)",
    longDesc: "The MESO-6 midrange speakers are designed for high-output pro audio systems. Featuring a lightweight paper cone and high-temperature voice coil, these speakers excel at reproducing vocals and instruments with authority. Perfect for 3-way active systems or as door speakers in high-power setups.",
    rating: 5,
    reviews: 52,
    currentPrice: "$119.99",
    originalPrice: "$169.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
    specs: [
      { label: "Size", value: '6.5"' },
      { label: "Type", value: "Midrange (Pair)" },
      { label: "Peak Power", value: "400W" },
      { label: "RMS Power", value: "150W" },
      { label: "Impedance", value: "4 Ohm" },
      { label: "Sensitivity", value: "94 dB" },
      { label: "Frequency Response", value: "100Hz - 8kHz" },
      { label: "Cone Material", value: "Pressed Paper" },
      { label: "Voice Coil", value: '1.5" High-Temp' },
      { label: "Magnet", value: "25 oz Ferrite" },
      { label: "Mounting Depth", value: '2.9"' },
    ],
    features: [
      "High-efficiency midrange design for pro audio",
      "Lightweight pressed paper cone for fast response",
      "1.5-inch high-temperature voice coil",
      "High SPL sensitivity (94 dB)",
      "Built for high-power active systems",
      "Vocal clarity that cuts through road noise",
      "Rugged steel basket construction",
      "Sold as a pair for left/right installation",
    ],
    whatsIncluded: ["2 x 6.5\" Midrange Speakers", "Mounting Hardware", "User Manual"],
    inStock: true,
  },
  "at-tweeter": {
    name: "AT-TWEETER",
    slug: "at-tweeter",
    series: "AT Series",
    category: "Speakers",
    categorySlug: "speakers",
    badge: "Sale",
    shortDesc: "1 Inch Silk Dome Tweeters (Pair)",
    longDesc: "The AT-TWEETER set features 1-inch silk dome tweeters engineered for smooth, detailed high-frequency reproduction. These tweeters can be surface or flush mounted, making them versatile for any installation. The included in-line crossover capacitors ensure proper frequency filtering for clean, distortion-free highs.",
    rating: 4,
    reviews: 38,
    currentPrice: "$49.99",
    originalPrice: "$79.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
    specs: [
      { label: "Tweeter Size", value: '1"' },
      { label: "Type", value: "Silk Dome (Pair)" },
      { label: "Peak Power", value: "120W" },
      { label: "RMS Power", value: "40W" },
      { label: "Impedance", value: "4 Ohm" },
      { label: "Sensitivity", value: "90 dB" },
      { label: "Frequency Response", value: "2kHz - 25kHz" },
      { label: "Dome Material", value: "Silk" },
      { label: "Magnet", value: "Neodymium" },
      { label: "Crossover", value: "In-line 12 dB/octave" },
      { label: "Mounting", value: "Surface / Flush Mount" },
    ],
    features: [
      "1-inch silk dome for smooth, natural highs",
      "Neodymium magnet for strong output",
      "Surface and flush mount options included",
      "In-line crossover capacitors for easy install",
      "Low distortion at high volumes",
      "Perfect upgrade for factory tweeters",
      "Compact housing fits tight spaces",
      "Sold as a pair",
    ],
    whatsIncluded: ["2 x 1\" Silk Dome Tweeters", "Surface Mount Housings", "Flush Mount Hardware", "In-line Crossovers", "Wiring", "User Manual"],
    inStock: true,
  },
  "meso-12-d2": {
    name: "MESO-12 D2",
    slug: "meso-12-d2",
    series: "Meso Series",
    category: "Subwoofers",
    categorySlug: "subwoofers",
    badge: "Best Seller",
    shortDesc: "1500W RMS 12-Inch Subwoofer Dual 2 Ohm",
    longDesc: "The MESO-12 D2 is a flagship 12-inch subwoofer built for extreme bass output. With 1500W RMS power handling, a massive motor structure, and a high-excursion surround, this subwoofer moves serious air. The dual 2 Ohm voice coils allow flexible wiring options for any amplifier setup. Engineered for competition-level performance in a daily driver package.",
    rating: 5,
    reviews: 89,
    currentPrice: "$189.99",
    originalPrice: "$279.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
    specs: [
      { label: "Size", value: '12"' },
      { label: "RMS Power", value: "1500W" },
      { label: "Peak Power", value: "3000W" },
      { label: "Voice Coil", value: "Dual 2 Ohm" },
      { label: "Sensitivity", value: "85.3 dB" },
      { label: "Frequency Response", value: "25Hz - 1.5kHz" },
      { label: "Cone Material", value: "Pressed Pulp" },
      { label: "Surround", value: "High-Roll Foam" },
      { label: "Voice Coil Diameter", value: '2.5"' },
      { label: "Magnet", value: "90 oz Ferrite" },
      { label: "Mounting Depth", value: '7.5"' },
      { label: "Cutout Diameter", value: '11.1"' },
    ],
    features: [
      "1500W RMS power handling",
      "Dual 2 Ohm voice coils for wiring flexibility",
      "2.5-inch high-temperature voice coil",
      "Massive 90 oz ferrite motor structure",
      "High-roll foam surround for extreme excursion",
      "Pressed pulp cone for warm, punchy bass",
      "Competition-level performance",
      "Ventilated pole piece for thermal management",
    ],
    whatsIncluded: ["MESO-12 D2 Subwoofer", "Gasket Ring", "User Manual"],
    inStock: true,
  },
  "abcde-15-d4": {
    name: "ABCDE-15 D4",
    slug: "abcde-15-d4",
    series: "ABCDE Series",
    category: "Subwoofers",
    categorySlug: "subwoofers",
    badge: "New",
    shortDesc: "2000W RMS 15-Inch Subwoofer Dual 4 Ohm",
    longDesc: "The ABCDE-15 D4 is a monster 15-inch subwoofer designed for the deepest, most authoritative bass. With 2000W RMS handling and a massive motor assembly, this subwoofer produces window-flexing low frequencies. The dual 4 Ohm configuration is ideal for high-power monoblock amplifiers. Built for those who refuse to compromise on bass output.",
    rating: 5,
    reviews: 34,
    currentPrice: "$249.99",
    originalPrice: "$349.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
    specs: [
      { label: "Size", value: '15"' },
      { label: "RMS Power", value: "2000W" },
      { label: "Peak Power", value: "4000W" },
      { label: "Voice Coil", value: "Dual 4 Ohm" },
      { label: "Sensitivity", value: "86.8 dB" },
      { label: "Frequency Response", value: "20Hz - 1.2kHz" },
      { label: "Cone Material", value: "Reinforced Pulp" },
      { label: "Surround", value: "High-Roll Foam" },
      { label: "Voice Coil Diameter", value: '3"' },
      { label: "Magnet", value: "120 oz Ferrite" },
      { label: "Mounting Depth", value: '8.5"' },
      { label: "Cutout Diameter", value: '13.9"' },
    ],
    features: [
      "2000W RMS - the most powerful ABCDE subwoofer",
      "Dual 4 Ohm voice coils for 2/8 Ohm wiring",
      "Massive 3-inch voice coil for thermal durability",
      "120 oz ferrite motor for extreme SPL",
      "Reinforced cone for high-pressure environments",
      "Deep bass response down to 20Hz",
      "Competition ready out of the box",
      "Engineered for large enclosures",
    ],
    whatsIncluded: ["ABCDE-15 D4 Subwoofer", "Gasket Ring", "User Manual"],
    inStock: true,
  },
  "meso-10-d4": {
    name: "MESO-10 D4",
    slug: "meso-10-d4",
    series: "Meso Series",
    category: "Subwoofers",
    categorySlug: "subwoofers",
    badge: "",
    shortDesc: "1000W RMS 10-Inch Subwoofer Dual 4 Ohm",
    longDesc: "The MESO-10 D4 delivers the perfect balance of punch and depth in a 10-inch package. With 1000W RMS power handling, this subwoofer is ideal for moderate-size enclosures while still producing impressive low-end output. The dual 4 Ohm voice coils offer versatile wiring options. Great for truck applications or anyone wanting tight, accurate bass.",
    rating: 4,
    reviews: 56,
    currentPrice: "$149.99",
    originalPrice: "$209.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
    specs: [
      { label: "Size", value: '10"' },
      { label: "RMS Power", value: "1000W" },
      { label: "Peak Power", value: "2000W" },
      { label: "Voice Coil", value: "Dual 4 Ohm" },
      { label: "Sensitivity", value: "84.5 dB" },
      { label: "Frequency Response", value: "28Hz - 1.5kHz" },
      { label: "Cone Material", value: "Pressed Pulp" },
      { label: "Surround", value: "High-Roll Foam" },
      { label: "Voice Coil Diameter", value: '2.5"' },
      { label: "Magnet", value: "70 oz Ferrite" },
      { label: "Mounting Depth", value: '6.5"' },
      { label: "Cutout Diameter", value: '9.2"' },
    ],
    features: [
      "1000W RMS power handling",
      "Dual 4 Ohm voice coils for flexible wiring",
      "Tight, punchy 10-inch bass response",
      "70 oz motor structure for strong output",
      "Ideal for sealed or ported enclosures",
      "Fits most truck and compact car applications",
      "High-roll surround for controlled excursion",
      "Great sound quality with impressive SPL",
    ],
    whatsIncluded: ["MESO-10 D4 Subwoofer", "Gasket Ring", "User Manual"],
    inStock: true,
  },
  "at-8-d2": {
    name: "AT-8 D2",
    slug: "at-8-d2",
    series: "AT Series",
    category: "Subwoofers",
    categorySlug: "subwoofers",
    badge: "Sale",
    shortDesc: "600W RMS 8-Inch Subwoofer Dual 2 Ohm",
    longDesc: "The AT-8 D2 is a compact 8-inch subwoofer that delivers surprising bass output for its size. With 600W RMS handling and dual 2 Ohm voice coils, it's perfect for motorcycle installations, under-seat applications, or anyone wanting bass in a small footprint. Don't let the size fool you - this sub moves serious air.",
    rating: 4,
    reviews: 29,
    currentPrice: "$89.99",
    originalPrice: "$129.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
    specs: [
      { label: "Size", value: '8"' },
      { label: "RMS Power", value: "600W" },
      { label: "Peak Power", value: "1200W" },
      { label: "Voice Coil", value: "Dual 2 Ohm" },
      { label: "Sensitivity", value: "83.2 dB" },
      { label: "Frequency Response", value: "35Hz - 1.5kHz" },
      { label: "Cone Material", value: "Polypropylene" },
      { label: "Surround", value: "Foam" },
      { label: "Voice Coil Diameter", value: '2"' },
      { label: "Magnet", value: "40 oz Ferrite" },
      { label: "Mounting Depth", value: '4.8"' },
      { label: "Cutout Diameter", value: '7.3"' },
    ],
    features: [
      "600W RMS in a compact 8-inch design",
      "Dual 2 Ohm voice coils for wiring to 1/4 Ohm",
      "Shallow mounting depth for tight spaces",
      "Perfect for motorcycles and under-seat installs",
      "Polypropylene cone for weather resistance",
      "Excellent bass-to-size ratio",
      "Fits most 8-inch factory sub locations",
      "Great value entry-level subwoofer",
    ],
    whatsIncluded: ["AT-8 D2 Subwoofer", "Gasket Ring", "User Manual"],
    inStock: true,
  },
  "sled-12-2000": {
    name: "SLED-12-2000",
    slug: "sled-12-2000",
    series: "Sled Series",
    category: "Sleds",
    categorySlug: "sleds",
    badge: "Best Seller",
    shortDesc: "12 Inch Sub + Enclosure + 2000W Amp Package",
    longDesc: "The SLED-12-2000 is a complete bass package featuring a 12-inch subwoofer, custom-tuned enclosure, and 2000W amplifier - all pre-matched for optimal performance. Just wire it up and enjoy massive bass output. The enclosure is precision-tuned for deep, punchy bass response, and the included amplifier is perfectly matched to the subwoofer's power handling.",
    rating: 5,
    reviews: 72,
    currentPrice: "$499.99",
    originalPrice: "$749.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
    specs: [
      { label: "Subwoofer Size", value: '12"' },
      { label: "Subwoofer RMS", value: "1500W" },
      { label: "Amplifier RMS", value: "2000W @ 1 Ohm" },
      { label: "Enclosure Type", value: "Vented (Ported)" },
      { label: "Enclosure Tuning", value: "38 Hz" },
      { label: "Wiring Kit", value: "0 Gauge Complete Kit Included" },
      { label: "Enclosure Volume", value: "2.25 cu ft" },
      { label: "Dimensions", value: '18" x 15" x 14.5"' },
      { label: "Total Weight", value: "38 lbs" },
      { label: "Impedance", value: "1 Ohm Final Load" },
    ],
    features: [
      "Complete plug-and-play bass system",
      "12-inch subwoofer with 1500W RMS handling",
      "Custom-tuned vented enclosure for maximum output",
      "2000W monoblock amplifier included",
      "0-gauge wiring kit with everything needed",
      "Precision-matched components for optimal performance",
      "Easy installation - just connect power and signal",
      "Enclosure finished in durable carpet",
    ],
    whatsIncluded: ["SLED-12-2000 12\" Subwoofer", "Vented Enclosure (pre-loaded)", "2000W Monoblock Amplifier", "0 Gauge Complete Wiring Kit", "Remote Bass Knob", "Installation Hardware", "User Manual"],
    inStock: true,
  },
  "sled-15-2500": {
    name: "SLED-15-2500",
    slug: "sled-15-2500",
    series: "Sled Series",
    category: "Sleds",
    categorySlug: "sleds",
    badge: "New",
    shortDesc: "15 Inch Sub + Enclosure + 2500W Amp Package",
    longDesc: "The SLED-15-2500 is the ultimate bass package for those who demand the most. This complete system includes a massive 15-inch subwoofer, a large vented enclosure, and a 2500W amplifier. The enclosure is tuned for maximum SPL while maintaining sound quality. If you want to be heard before you're seen, this is the package for you.",
    rating: 5,
    reviews: 28,
    currentPrice: "$649.99",
    originalPrice: "$899.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
    specs: [
      { label: "Subwoofer Size", value: '15"' },
      { label: "Subwoofer RMS", value: "2000W" },
      { label: "Amplifier RMS", value: "2500W @ 1 Ohm" },
      { label: "Enclosure Type", value: "Vented (Ported)" },
      { label: "Enclosure Tuning", value: "36 Hz" },
      { label: "Wiring Kit", value: "0 Gauge Complete Kit Included" },
      { label: "Enclosure Volume", value: "3.5 cu ft" },
      { label: "Dimensions", value: '22" x 18" x 16"' },
      { label: "Total Weight", value: "52 lbs" },
      { label: "Impedance", value: "1 Ohm Final Load" },
    ],
    features: [
      "Maximum power complete bass system",
      "15-inch subwoofer with 2000W RMS handling",
      "Large vented enclosure tuned for SPL",
      "2500W monoblock amplifier included",
      "0-gauge complete wiring kit",
      "Designed for competition-level output",
      "Pre-wired and ready to install",
      "Reinforced enclosure construction",
    ],
    whatsIncluded: ["SLED-15-2500 15\" Subwoofer", "Vented Enclosure (pre-loaded)", "2500W Monoblock Amplifier", "0 Gauge Complete Wiring Kit", "Remote Bass Knob", "Installation Hardware", "User Manual"],
    inStock: true,
  },
  "sled-10-1200": {
    name: "SLED-10-1200",
    slug: "sled-10-1200",
    series: "Sled Series",
    category: "Sleds",
    categorySlug: "sleds",
    badge: "",
    shortDesc: "10 Inch Sub + Enclosure + 1200W Amp Package",
    longDesc: "The SLED-10-1200 is a balanced bass package perfect for those who want quality bass without sacrificing too much trunk space. Featuring a 10-inch subwoofer, compact vented enclosure, and 1200W amplifier, this system delivers punchy, accurate bass that's perfect for daily listening. An excellent value for a complete, ready-to-install system.",
    rating: 4,
    reviews: 45,
    currentPrice: "$379.99",
    originalPrice: "$529.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
    specs: [
      { label: "Subwoofer Size", value: '10"' },
      { label: "Subwoofer RMS", value: "1000W" },
      { label: "Amplifier RMS", value: "1200W @ 1 Ohm" },
      { label: "Enclosure Type", value: "Vented (Ported)" },
      { label: "Enclosure Tuning", value: "40 Hz" },
      { label: "Wiring Kit", value: "4 Gauge Complete Kit Included" },
      { label: "Enclosure Volume", value: "1.25 cu ft" },
      { label: "Dimensions", value: '14" x 12" x 11"' },
      { label: "Total Weight", value: "24 lbs" },
      { label: "Impedance", value: "1 Ohm Final Load" },
    ],
    features: [
      "Compact complete bass system",
      "10-inch subwoofer with 1000W RMS handling",
      "Space-saving vented enclosure design",
      "1200W monoblock amplifier included",
      "4-gauge complete wiring kit",
      "Perfect for daily driver applications",
      "Quick and easy installation",
      "Great bass in a small footprint",
    ],
    whatsIncluded: ["SLED-10-1200 10\" Subwoofer", "Vented Enclosure (pre-loaded)", "1200W Monoblock Amplifier", "4 Gauge Complete Wiring Kit", "Remote Bass Knob", "Installation Hardware", "User Manual"],
    inStock: true,
  },
  "sled-8-800": {
    name: "SLED-8-800",
    slug: "sled-8-800",
    series: "Sled Series",
    category: "Sleds",
    categorySlug: "sleds",
    badge: "Sale",
    shortDesc: "8 Inch Sub + Enclosure + 800W Amp Package",
    longDesc: "The SLED-8-800 is the most compact bass package in the ABCDE lineup, perfect for trucks, motorcycles, or anyone with limited space. Despite its small size, this 8-inch subwoofer and 800W amplifier combination produces impressive bass. The ultra-compact enclosure fits under most seats or behind truck seats, making it the ideal space-saving solution.",
    rating: 4,
    reviews: 19,
    currentPrice: "$299.99",
    originalPrice: "$429.99",
    image: "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
    specs: [
      { label: "Subwoofer Size", value: '8"' },
      { label: "Subwoofer RMS", value: "600W" },
      { label: "Amplifier RMS", value: "800W @ 1 Ohm" },
      { label: "Enclosure Type", value: "Sealed" },
      { label: "Wiring Kit", value: "8 Gauge Complete Kit Included" },
      { label: "Enclosure Volume", value: "0.5 cu ft" },
      { label: "Dimensions", value: '10" x 8" x 7.5"' },
      { label: "Total Weight", value: "14 lbs" },
      { label: "Impedance", value: "1 Ohm Final Load" },
    ],
    features: [
      "Ultra-compact complete bass system",
      "8-inch subwoofer with 600W RMS handling",
      "Sealed enclosure for tight, accurate bass",
      "800W monoblock amplifier included",
      "8-gauge complete wiring kit",
      "Fits under seats and in tight spaces",
      "Perfect for trucks and motorcycles",
      "Plug-and-play installation",
    ],
    whatsIncluded: ["SLED-8-800 8\" Subwoofer", "Sealed Enclosure (pre-loaded)", "800W Monoblock Amplifier", "8 Gauge Complete Wiring Kit", "Installation Hardware", "User Manual"],
    inStock: true,
  },
};

// Helper: get product detail by slug
export function getProductDetail(slug: string): ProductDetailData | null {
  return productDetails[slug] || null;
}

// Helper: get related products from same category
export function getRelatedProducts(categorySlug: string, currentSlug: string): ProductCardData[] {
  const catData = categoryData[categorySlug];
  if (!catData) return [];
  return catData.products.filter((p) => p.slug !== currentSlug).slice(0, 3);
}

export const categoryData: Record<string, CategoryPageData> = {
  amplifiers: {
    title: "Amplifiers",
    accent: "Series",
    subtitle: "Power Your Sound System",
    heroImage:
      "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
    description:
      "ABCDE amplifiers deliver clean, powerful sound with Class D technology. From monoblock to multi-channel, we have the perfect amp for your build.",
    products: [
      {
        badge: "Best Seller",
        series: "ABCDE Series",
        name: "ABCDE-2000.1D",
        slug: "abcde-2000-1d",
        description: "2000W RMS Monoblock Class D Amplifier",
        rating: 5,
        reviews: 127,
        currentPrice: "$299.99",
        originalPrice: "$449.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
      },
      {
        badge: "New",
        series: "AT Series v2",
        name: "ATv2-200.4D",
        slug: "atv2-200-4d",
        description: "4-Channel Class D Amplifier",
        rating: 4,
        reviews: 54,
        currentPrice: "$229.99",
        originalPrice: "$329.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
      },
      {
        badge: "",
        series: "ABCDE Series",
        name: "ABCDE-1000.4D",
        slug: "abcde-1000-4d",
        description: "1000W 4-Channel Class D Amplifier",
        rating: 5,
        reviews: 89,
        currentPrice: "$199.99",
        originalPrice: "$279.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
      },
      {
        badge: "Sale",
        series: "AT Series",
        name: "AT-1200.1D",
        slug: "at-1200-1d",
        description: "1200W RMS Monoblock Amplifier",
        rating: 4,
        reviews: 67,
        currentPrice: "$159.99",
        originalPrice: "$229.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/amplifiers-corrected_650x.jpg?v=1676307831",
      },
    ],
  },
  speakers: {
    title: "Speakers",
    accent: "Collection",
    subtitle: "Crystal Clear Sound",
    heroImage:
      "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
    description:
      "Experience premium sound quality with ABCDE speakers. From component systems to coaxial, our speakers deliver crystal clear highs and deep mids.",
    products: [
      {
        badge: "Best Seller",
        series: "Meso Series",
        name: "MESO-6.5",
        slug: "meso-6-5",
        description: "6.5 Inch 2-Way Component Speaker System",
        rating: 5,
        reviews: 94,
        currentPrice: "$149.99",
        originalPrice: "$199.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
      },
      {
        badge: "New",
        series: "AT Series",
        name: "AT-6X9",
        slug: "at-6x9",
        description: "6x9 Inch 3-Way Coaxial Speakers",
        rating: 4,
        reviews: 41,
        currentPrice: "$89.99",
        originalPrice: "$129.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
      },
      {
        badge: "",
        series: "Meso Series",
        name: "MESO-6",
        slug: "meso-6",
        description: "6.5 Inch Midrange Speaker (Pair)",
        rating: 5,
        reviews: 52,
        currentPrice: "$119.99",
        originalPrice: "$169.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
      },
      {
        badge: "Sale",
        series: "AT Series",
        name: "AT-TWEETER",
        slug: "at-tweeter",
        description: "1 Inch Silk Dome Tweeters (Pair)",
        rating: 4,
        reviews: 38,
        currentPrice: "$49.99",
        originalPrice: "$79.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/speakers_650x.jpg?v=1664730896",
      },
    ],
  },
  subwoofers: {
    title: "Subwoofers",
    accent: "Lineup",
    subtitle: "Feel The Bass",
    heroImage:
      "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
    description:
      "ABCDE subwoofers are built for bass enthusiasts. With high-power handling and precision engineering, our subs deliver earth-shaking low frequencies.",
    products: [
      {
        badge: "Best Seller",
        series: "Meso Series",
        name: "MESO-12 D2",
        slug: "meso-12-d2",
        description: "1500W RMS 12-Inch Subwoofer Dual 2 Ohm",
        rating: 5,
        reviews: 89,
        currentPrice: "$189.99",
        originalPrice: "$279.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
      },
      {
        badge: "New",
        series: "ABCDE Series",
        name: "ABCDE-15 D4",
        slug: "abcde-15-d4",
        description: "2000W RMS 15-Inch Subwoofer Dual 4 Ohm",
        rating: 5,
        reviews: 34,
        currentPrice: "$249.99",
        originalPrice: "$349.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
      },
      {
        badge: "",
        series: "Meso Series",
        name: "MESO-10 D4",
        slug: "meso-10-d4",
        description: "1000W RMS 10-Inch Subwoofer Dual 4 Ohm",
        rating: 4,
        reviews: 56,
        currentPrice: "$149.99",
        originalPrice: "$209.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
      },
      {
        badge: "Sale",
        series: "AT Series",
        name: "AT-8 D2",
        slug: "at-8-d2",
        description: "600W RMS 8-Inch Subwoofer Dual 2 Ohm",
        rating: 4,
        reviews: 29,
        currentPrice: "$89.99",
        originalPrice: "$129.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/subwoofers1_650x.jpg?v=1664730876",
      },
    ],
  },
  sleds: {
    title: "Sleds",
    accent: "& Enclosures",
    subtitle: "Ready-To-Run Bass Packages",
    heroImage:
      "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
    description:
      "ABCDE Sleds are complete bass packages with subwoofer, enclosure, and amplifier pre-matched for optimal performance. Just install and enjoy.",
    products: [
      {
        badge: "Best Seller",
        series: "Sled Series",
        name: "SLED-12-2000",
        slug: "sled-12-2000",
        description: "12 Inch Sub + Enclosure + 2000W Amp Package",
        rating: 5,
        reviews: 72,
        currentPrice: "$499.99",
        originalPrice: "$749.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
      },
      {
        badge: "New",
        series: "Sled Series",
        name: "SLED-15-2500",
        slug: "sled-15-2500",
        description: "15 Inch Sub + Enclosure + 2500W Amp Package",
        rating: 5,
        reviews: 28,
        currentPrice: "$649.99",
        originalPrice: "$899.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
      },
      {
        badge: "",
        series: "Sled Series",
        name: "SLED-10-1200",
        slug: "sled-10-1200",
        description: "10 Inch Sub + Enclosure + 1200W Amp Package",
        rating: 4,
        reviews: 45,
        currentPrice: "$379.99",
        originalPrice: "$529.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
      },
      {
        badge: "Sale",
        series: "Sled Series",
        name: "SLED-8-800",
        slug: "sled-8-800",
        description: "8 Inch Sub + Enclosure + 800W Amp Package",
        rating: 4,
        reviews: 19,
        currentPrice: "$299.99",
        originalPrice: "$429.99",
        image:
          "https://cdn.shopify.com/s/files/1/1690/0705/files/wiring-kits_650x.jpg?v=1664730938",
      },
    ],
  },
};
